definitions:
  check_nik.CheckNIKResp:
    properties:
      city:
        type: string
      district:
        type: string
      name:
        type: string
      nik:
        type: string
      nkk:
        type: string
      nrt:
        type: string
      nrw:
        type: string
      subdistrict:
        type: string
      tps_address:
        type: string
      tps_no:
        type: string
    type: object
  dto.Response-check_nik_CheckNIKResp:
    properties:
      data:
        $ref: '#/definitions/check_nik.CheckNIKResp'
      error: {}
      message:
        type: string
    type: object
  dto.Response-string:
    properties:
      data:
        type: string
      error: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: API for checking NIK in the voter database
  title: DPB Online API
  version: 0.1.0
paths:
  /{nik}:
    get:
      description: Lookup pemilih (voter) data by NIK using a path parameter.
      parameters:
      - description: NIK
        in: path
        name: nik
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response-check_nik_CheckNIKResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response-string'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response-string'
      summary: Check NIK (path)
      tags:
      - Voter
  /check:
    get:
      description: Lookup pemilih (voter) data by NIK using a query parameter.
      parameters:
      - description: NIK
        in: query
        name: nik
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response-check_nik_CheckNIKResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response-string'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response-string'
      summary: Check NIK (query)
      tags:
      - Voter
swagger: "2.0"
